name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Deploy-Gcloud-Function:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v1
        with:
          # credentials_json: "${{ secrets.GSERVICE_ACCCOUNT }}"
          workload_identity_provider: "projects/1066668716061/locations/global/workloadIdentityPools/github-actions/providers/github-actions "
          service_account: "cost-my-chemo-bot@cost-my-chemo-bot.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - id: "prepare_env"
        run: >
          echo "${{ secrets.CLOUD_ENV }}" > cloud_env.yaml

      - id: "deploy"
        run: >
          make deploy
